server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petdb?
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
#    schema: classpath:database/schema.sql
#    data: classpath:database/data.sql
    sql-script-encoding: utf-8